/**
 * Standard API error codes.
 * Source of truth: docs/api-spec.md §9 (Mã lỗi).
 */
export const ApiErrorCode = {
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  UNAUTHORIZED: 'UNAUTHORIZED',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  MEETING_NOT_FOUND: 'MEETING_NOT_FOUND',
  NOT_FOUND: 'NOT_FOUND',
  INVALID_STATE_TRANSITION: 'INVALID_STATE_TRANSITION',
  SEGMENTS_PENDING: 'SEGMENTS_PENDING',
  MEETING_NOT_READY: 'MEETING_NOT_READY',
  PROCESSING_FAILED: 'PROCESSING_FAILED',
  QUOTA_EXCEEDED: 'QUOTA_EXCEEDED',
  RATE_LIMITED: 'RATE_LIMITED',
  AI_SERVICE_UNAVAILABLE: 'AI_SERVICE_UNAVAILABLE',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
} as const;

export type ApiErrorCode = (typeof ApiErrorCode)[keyof typeof ApiErrorCode];
